### ISSUE TITLE
branch name for z3.0.x

### ISSUE THREAD

**Issue by cryptozeny** [bitzenyPlus/BitZenyPlus#11]
以前にargon2dテストのためのz3.0.xブランチがすでにいる。 yespowerブランチも同じバージョンになれば、混乱がある。 ブランチ名整理が必要である。

**Comment by hitobb** [comment]
argon2dテストのためのz3.0.xブランチをリネームします。

**Comment by cryptozeny** [comment]
どんなことにしましょうか。

 * `z3.0.x`
 * `z3.0.x-yespower0.5`

すでに`z3.0.x`ブランチにコードが入っています。 整理してくだされば感謝します。@hitobb 

`feature/yespower-0.5`は消さないでください。 PRも消えることができます。

**Comment by shuichiro-makigaki** [comment]
As the brand new BitZeny, the branch name "v3.0.0" may be redundant. Also, we don't need to have v2.x and older branches.

Some of my ideas:
* Use master branch for development, and fork versioned branch for new stable releases.
  * This is the same as the Bitcoin? (not confirmed)
* Keep using versioned branch for active development like now
  * But older branches should be removed?
* Others

**Comment by cryptozeny** [comment]
> Use master branch for development

i agree we need `master` branch i think

**Comment by bellflower2015** [comment]
I think we need `v3.0-dev` branch like as `git-flow`'s develop branch.
And `v3.0` (or `v3.0-rel(ease)`) branch prefer to use as release branch.
(To name as `vN.N` and `vN.N-dev` is easy to understood and simple)
So dev branch will merge and delete after releasing it, and create next version's dev and there is **only one dev** branch, and **many release** tag.

**Comment by bellflower2015** [comment]
To simply to say, like as follows:
- `vN.N.N` ... tag (already released)
- `vN.N`or `vN.N-rel` or `vN.N-release` ... release branch (but not released yet)
- `vN.N-dev` ... develop branch (working branch)

**Comment by hitobb** [comment]
There are two management methods.

- Following BitCoin
- Following GitBranchModel
  ( https://nvie.com/posts/a-successful-git-branching-model/)

Personally I want to Following the BitCoin.

---

I can not agree to create a master branch.
If we do not write the version in the branch name, different BitCoin based sources may mix.
Mixing the sources of 1.2.x and 1.3.x has happened in the past.

**Comment by bellflower2015** [comment]
Discord上での話し合いの結果、

- `v3.0-dev` ... developブランチ
- `v3.0-rel` ... releaseブランチ(リリース準備開始とともに作成、リリース完了後に削除)
- `v3.0` ... masterブランチ(`v3.0.0.0`リリース完了後に作成)
- `feature`, `hotfix` ... git-flowに準拠

と決まりました。

**Comment by bellflower2015** [comment]
[Wiki](https://github.com/bitzenyPlus/BitZenyPlus/wiki/Rules-for-Developing-BitZeny-Plus-(%E9%96%8B%E7%99%BA%E3%83%AB%E3%83%BC%E3%83%AB))に記載しました。
