### ISSUE TITLE
ディレクトリ名等を "BitZeny" ⇒ "BitZenyPlus" にしてはどうか

### ISSUE THREAD

**Issue by bellflower2015** [bitzenyPlus/BitZenyPlus#13]
`util.cpp`

- BITCOIN_CONF_FILENAME
- BITCOIN_PID_FILENAME
- GetDefaultDataDir()

`s/BitZeny/BitZenyPlus/g`
`s/bitzeny/bitzenyplus/g`

**Comment by cryptozeny** [comment]
良いアイデアです! ところで`sed`で全部変えるのが安全ですか。:thinking:

**Comment by bellflower2015** [comment]
@cryptozeny 
修正箇所は `util.cpp` の上記3箇所だけだと思います。
予期しない場所が変更されるかもしれないので、`sed`は使わなくて良いと思います。

しかしその前に、
「変えない」vs「変える」：検討しなければなりません。

**Comment by hitobb** [comment]
「BitZenyPlus」に変更する案を支持します。

**Comment by bellflower2015** [comment]
- BITCOIN_CONF_FILENAME
- BITCOIN_PID_FILENAME

この2つはそのままとします。(`bitzeny.conf` , `bitzeny.pid`)
ここも変えてしまうと、`bitzenyd`なんかも`bitzenyplusd`にすべき、となってしまって割とキリがない。

**Comment by cryptozeny** [comment]
merged #20
