### ISSUE TITLE
about dialogのURL

### ISSUE THREAD

**Issue by bellflower2015** [bitzenyPlus/BitZenyPlus#14]
下記2項目をどうするか決定しなければならない。
- http://bitzeny.org
- https://github.com/BitzenyCoreDevelopers/bitzeny

**Comment by cryptozeny** [comment]
it should be fixed... thanks for report!

![about bitzeny core_107](https://user-images.githubusercontent.com/37016180/43662799-0eacc236-97a2-11e8-8258-37d266cb90fd.png)

 * http://bitzeny.org
 * https://github.com/BitzenyCoreDevelopers/bitzeny
 * The BitZeny Core developers >> `bitzenyPlus developers` ??

**Comment by hitobb** [comment]
I think this is better.

---

http://bitzeny.org >> https://bitzeny.tech

https://github.com/BitzenyCoreDevelopers/bitzeny >> https://github.com/bitzenyPlus/bitzeny

The BitZeny Core developers >> The BitZeny Core developers + The BitZenyPlus developers

**Comment by cryptozeny** [comment]
@hitobb 
> The BitZeny Core developers + The BitZenyPlus developers

あまりにも冗長ではないか? とても長い。
:thinking:

**Comment by cryptozeny** [comment]
https://github.com/cryptozeny/bitzeny/blob/ea042b862765fa45475930ec869594309afbdc43/src/crypto/yespower-bitzeny.c#L2

https://github.com/cryptozeny/bitzeny/blob/ea042b862765fa45475930ec869594309afbdc43/src/crypto/yespower-bitzeny.c#L26

these lines also should be checked

**Comment by cryptozeny** [comment]
![screenshot from 2018-08-06 05-21-30](https://user-images.githubusercontent.com/37016180/43689642-9c9aa332-9938-11e8-88b6-f45f3e683348.png)

margin and scroll bar

**Comment by bellflower2015** [comment]
@cryptozeny 
それはURLの問題ではないので、話題が違います。
新たなIssueを立てましょう。

**Comment by cryptozeny** [comment]
about dialogの問題に統合可能か?

**Comment by bellflower2015** [comment]
@cryptozeny 
問題を分けておかなければ、個別にcloseできなくなるためです。

**Comment by cryptozeny** [comment]
新たにissueを開きます。

**Comment by hitobb** [comment]
@cryptozeny 

>The BitZeny Core developers + The BitZenyPlus developers
>
>あまりにも冗長ではないか? とても長い。

Copyright MUST NOT be deleted for design reasons.
https://ja.wikipedia.org/wiki/MIT_License

btw,I agree to modify the design.

**Comment by kazu0617** [comment]
I think `The BitZeny Core developers` and `The BitZenyPlus developers` can be separated into two paragraphs because now BitZeny Core and BitZenyPlus are not same repos.
自分が思うにBitZenyCoreDevelopersとBitZenyPlusDevelopersとは別のリポジトリを持っているので二行に分けれる（それならきれいになる気がする）。
@cryptozeny @hitobb

**Comment by cryptozeny** [comment]
@kazu0617

開発チームが異なるため、二つの列にすることに賛成する。

**Comment by kazu0617** [comment]
このプルリクで一まずOKかと思われるのでクローズします。
