### ISSUE TITLE
表記の揺れが気持ち悪い

### ISSUE THREAD

**Issue by bellflower2015** [bitzenyPlus/BitZenyPlus#15]
- bitzenyPlus
- BitZenyPlus
- BitZeny Plus
- etcetc.

正式な表記を確定してほしい。

**Comment by cryptozeny** [comment]
:thinking:

**Comment by hitobb** [comment]
正式には「BitZenyPlus」
（＝Bit（電子）のZeny、Plus版）

githubのリポジトリが「bitzenyPlus」の理由は、

https://github.com/bitzeny

に「Plus」をつけると

https://github.com/bitzenyPlus

へリンクする為。

シンボルフォントが全部小文字になっているのは、デザイン重視のため。
