### ISSUE TITLE
aesthetic issue: symbol font mismatch

### ISSUE THREAD

**Issue by cryptozeny** [bitzenyPlus/BitZenyPlus#17]
現在、シンボルマークのフォントです。
![40815976](https://user-images.githubusercontent.com/37016180/43685688-88af9e18-98f2-11e8-839e-87abc4f1af30.jpeg)

全部`小文字`になっている。

分かち書き不明
```
bitzeny plus 

VS 

bitzenyplus
```

しかし、表記法は

`P`大文字
```
bitzenyPlus
```

あるいは

`B、Z、P`大文字
```
BitZenyPlus
```

としている。

表記法が少し混乱しています。:thinking:

https://github.com/bitzenyPlus/BitZenyPlus/issues/13

https://github.com/bitzenyPlus/BitZenyPlus/issues/14

https://github.com/bitzenyPlus/BitZenyPlus/issues/8

**Comment by bellflower2015** [comment]
#15 と同じ問題です。
