### ISSUE TITLE
暗い背景でアイコンが見づらい問題

### ISSUE THREAD

**Issue by bellflower2015** [bitzenyPlus/BitZenyPlus#22]
例：
Ubuntu (unity)
![43708809-40f2d522-99a6-11e8-9a80-33007ef55027](https://user-images.githubusercontent.com/12813420/43719693-593b21a2-99c9-11e8-9483-217d36381486.png)
Windows10
![screen shot 2018-08-06 at 22 30 46](https://user-images.githubusercontent.com/12813420/43719701-5f47f336-99c9-11e8-8e55-2a33acfd6172.png)

現状は、元素材は
https://github.com/bitzenyPlus/symbol_mark/blob/master/png/bitzenyplus-symbol-1024.png
であり、ソースコード上のリソースは
`src/qt/res/icons/bitcoin.icns`である。

素材の性格上、あらゆる背景でも見やすいアイコンにすることが難しいので、可能であればアイコン用に対策された素材を用意したい。できれば専門家（理想はロゴ作者様）に任せたい。

**Comment by zinntikumugai** [comment]
Discordのリアクションように私が加工したものを
https://github.com/bitzenyPlus/BitZenyPlus/pull/19#issuecomment-410703693
に置いてあります(サンプルとして一応)

**Comment by cryptozeny** [comment]
ユーザーが失望することができる。 必ず直さなければならない。!!

**Comment by cryptozeny** [comment]
まだ問題があります。 デザイナーに助けを要請するのはどうですか?

**Comment by glen040417** [comment]
ロゴ作者のぐれんといいます。いつもお世話になってます。

ー

bitzeny.tech → https://bitzeny.tech/ にあるように、
色を白に変換しようと思います。

背景が暗い場合の対策として、
githubに色を白に変換したデータもあらかじめ用意しておくのが、
親切かなと思ったので、そこに関してはひとばしらさんと話し合ってきめますね。

github bitzenyplus - https://github.com/bitzenyPlus/symbol_mark
github bitzeny - https://github.com/BitzenyCoreDevelopers/logo

bellflower2015さん、ご意見ありがとうございました。

**Comment by hitobb** [comment]
@glen040417

いつもありがとうございます。
こちらの皆さんの意見を優先して取り上げていただけると助かります。

**Comment by cryptozeny** [comment]
![1533643285](https://user-images.githubusercontent.com/37016180/43780336-4deeaa22-9a95-11e8-9ee6-15081a19df1a.png)


http://gall.dcinside.com/bitzeny/1736

どんな韓国ユーザのアイコンが暗くて見えないという意見。

**Comment by glen040417** [comment]
ひとばしらさん、

「こちらの皆さんの意見」というのはどの意見でしょうか？
おそらくURLが反映されてないと思うのですが。

**Comment by zinntikumugai** [comment]
@glen040417 
DisocrdやPR/issuesでのことを指しているかと

![img](https://cdn.discordapp.com/attachments/474283531112284160/476019617710735368/unknown.png)
主に、各種環境によるタスクバーではたいへん見づらいので製作、専門家の意見がほしい形です
上の方であげましたように私がDiscordのリアクションで使う際の加工したものなども上げております

(できればDiscordリアクションも見づらい(同化してる)のでそこらへんも考慮or追加してもらえれば幸いです)
![image](https://user-images.githubusercontent.com/16275962/43781812-c4e27f0c-9a98-11e8-80e8-2e9b9070c8a6.png)

**Comment by hitobb** [comment]
@glen040417

私の文章が足りておらず、申し訳ありません。

「このissueに投稿している、hitobb以外のみなさんの意見を取り込んだ上で「アイコン用のシンボルマーク」デザインをご検討ください」の意味です。

**Comment by glen040417** [comment]
bellflower2015 さんの画像をおかりしますが、
背景がダークだった場合として、↓のようなデザインを提案します。
（白にするか、全体的に明度をあげたものにするのか）

![43719701-5f47f336-99c911e8-8e55-2a33acfd6172](https://user-images.githubusercontent.com/34239469/43782748-fc8e62a2-9a9a-11e8-9a2e-33e6c1797808.png)

![43719701-5f47f336-99c9-11e8-8e55-2a33acfd6172](https://user-images.githubusercontent.com/34239469/43782735-f67adad0-9a9a-11e8-972e-ae6eab43e807.png)

zinntikumugai さん、返信ありがとうございます。
DiscordとPR/issues 先ほど確認させていただきました。

**Comment by glen040417** [comment]
![0j](https://user-images.githubusercontent.com/34239469/43783943-e7ced614-9a9d-11e8-973f-1ee1397fbcfb.png)

![092](https://user-images.githubusercontent.com/34239469/43783949-eb1925d6-9a9d-11e8-9829-642bd0150564.png)

↑ - Ubuntu (unity) の場合 -

**Comment by cryptozeny** [comment]
2回目ともにホワイトがいいですね!

**Comment by glen040417** [comment]
もし、なにか問題があるようでしたら、ぜひコメントください。

これで問題ないようであれば、
↓のデザインをgithubにあげようと思います。

![43719701-5f47f336-99c911e8-8e55-2a33acfd6172](https://user-images.githubusercontent.com/34239469/43785299-f68dde72-9aa0-11e8-9e50-fee2df2e1ad1.png)
　
![0j](https://user-images.githubusercontent.com/34239469/43785065-8521654c-9aa0-11e8-9b18-dca9cd8cfcca.png)

**Comment by glen040417** [comment]
cryptozeny さんコメントありがとうございます^^

**Comment by cryptozeny** [comment]
階調がいない方がもっと綺麗なようだ。😅

**Comment by kazu0617** [comment]
![](https://user-images.githubusercontent.com/34239469/43782735-f67adad0-9a9a-11e8-972e-ae6eab43e807.png)
![](https://user-images.githubusercontent.com/34239469/43783949-eb1925d6-9a9d-11e8-9829-642bd0150564.png)

こちらのほうが良いな、と思いました（白ベタであってるのか気になったのでコメント編集しましたが、内容は同じです）

**Comment by glen040417** [comment]
コメントありがとうございます。

今のところ白ベタのほうがいいという意見が多いですね。
ある程度コメントいただいた上で、最終的にどちらを用意するか決めようとおもいますb

**Comment by bellflower2015** [comment]
@glen040417 
おお、降臨されている。
呼び掛けた甲斐がありました。ありがとうございます。

私が懸念しているのは、「暗い背景用に寄せると、こんどは明るい背景で視認性が落ちる」です。
両立するためのアイデアがほしいです。

要するに、アプリは「背景が暗いか明るいか」はわからないし、それを判別してロゴを出し分ける事もできません。

**Comment by bellflower2015** [comment]
> 要するに、アプリは「背景が暗いか明るいか」はわからないし、それを判別してロゴを出し分ける事もできません。

透過画像である以上は。という意味です。

**Comment by zinntikumugai** [comment]
![img](https://camo.githubusercontent.com/5e2bfd875ac007792dafbc0463624cc86a700792/68747470733a2f2f692e696d6775722e636f6d2f363055683056502e706e67)

私の中では画像のようなものなら両対応できるかなと(Discordで(ry
https://github.com/bitzenyPlus/BitZenyPlus/pull/19#issuecomment-410703693 より

強いて言えば中埋め+外周に加工したものが見やすいいかなと (コレもDiscordで言われたものですが

**Comment by zinntikumugai** [comment]
![img](https://camo.githubusercontent.com/fc1f69c46d2943592b0822a7cc5702263c2aa734/68747470733a2f2f692e696d6775722e636f6d2f593761777334622e706e67)
自分の理想が[ここ](https://github.com/bitzenyPlus/BitZenyPlus/pull/19#issuecomment-410703693)にあった
(透過部分がGitHubの背景に同化していますのでファイル単体で見るとベストです)

**Comment by cryptozeny** [comment]
@bellflower2015 ほとんどのosがdark themeを書いている。 違うのか？

**Comment by kazu0617** [comment]
@bellflower2015 @cryptozeny 
I checked theme on windows, but no one support light theme, even windows official icon.
So, I think it is ok to think under dark theme.
Windows上で確認した限りでは、Windowsの公式アイコンでさえもライトテーマに対応していませんでした。そのため、少なくともタスクバーにおいては暗い背景ってことを前提に考えてよさそうです。
![image](https://user-images.githubusercontent.com/6259214/43798290-1843dfe8-9ac5-11e8-9dfd-3783354b3b7f.png)
![image](https://user-images.githubusercontent.com/6259214/43798301-2171c0b2-9ac5-11e8-9ed7-5fdc2dcf0a85.png)

**Comment by bellflower2015** [comment]
ぐれん氏とLINEで話しました。
結論をいうと

* 暗い背景、明るい背景でどちらでも視認性がよく、それでいて見た目も美しい素材は難しい
* 新たに暗い背景用に素材（[bitzeny.tech](https://bitzeny.tech/)のような白抜き）を用意することは可能
* 総合的には「アプリアイコン用は透過をやめて白ベタ背景の上にロゴを乗せる」形がベターであろう

という内容でした。
ので、「アプリアイコン用は透過をやめて白ベタ背景の上にロゴを乗せる」の方向で一度修正してみてまたここにスクショ貼ろうと思います。

@glen040417 認識に齟齬があれば補足してください。

**Comment by bellflower2015** [comment]
補足。というか追加？

* @glen040417 先にぐれん氏に提案いただいていたものも、githubに上げていただければ試したいです。
* @cryptozeny @kazu0617 完全白抜きの方がいい、という意見もありましたが、例えばexplorer.exeなどのfilerで視認したときに（白背景）完全に見えなくなるおそれがあるため却下したいです。
* @zinntikumugai 氏の案はぐれん氏の感想を聞いてみたい。

**Comment by cryptozeny** [comment]
![screenshot from 2018-08-09 10-25-50](https://user-images.githubusercontent.com/37016180/43872909-0ad299a8-9bbf-11e8-9281-cc97935ac557.png)

**Comment by glen040417** [comment]
桔梗さん、まとめありがとうございます。

・暗い背景、明るい背景でどちらでも視認性がよく、それでいて見た目も美しい素材は難しい

＞今回のアプリ用に以下のデザインを提案させていただきます。①

![3](https://user-images.githubusercontent.com/34239469/43885461-ed4e53ce-9bf3-11e8-8d64-ce7e0551680b.png)

![1](https://user-images.githubusercontent.com/34239469/43885466-f226a6f8-9bf3-11e8-8df9-2dd9bc4de89d.png)

![2](https://user-images.githubusercontent.com/34239469/43885493-ff4ea984-9bf3-11e8-933e-69e90b745b0a.png)

これであれば、上記の問題点をクリアできると思います。
（このデータは桔梗さんにお渡しできます。）

・新たに暗い背景用に素材（bitzeny.techのような白抜き）を用意することは可能

＞新たにデータを作成し、素材ごとにひとばしらさんにgithubのほうにあげていただきました。

BitZeny Plus - github  https://github.com/bitzenyPlus/symbol_mark

BitZeny - github  https://github.com/BitzenyCoreDevelopers/logo

image↓

![- 2](https://user-images.githubusercontent.com/34239469/43885677-7eeeaf90-9bf4-11e8-8fc3-114478819cf0.png)

![- 1](https://user-images.githubusercontent.com/34239469/43885692-8812ae14-9bf4-11e8-935e-d5d6b8e04b52.png)

![- 3](https://user-images.githubusercontent.com/34239469/43885684-83e3508c-9bf4-11e8-800c-30b0e5c8bf2f.png)

これで状況にあわせてgithubからdlしていただけるかなと思います。

・総合的には「アプリアイコン用は透過をやめて白ベタ背景の上にロゴを乗せる」形がベターであろう

＞この場合、背景も”形”としてあらわれることから、できるだけ全体としてデザインが成り立つようにしたい。

そこで↑①をぐれんは提案します。

ーーー

あらためて、桔梗さん、一昨日はありがとうございました。^^

**Comment by cryptozeny** [comment]
@bellflower2015 @glen040417 

どうも。 ところが、greyの背景が不完全な感じを与えるようです。 これが最善なんですか?

![43885493-ff4ea984-9bf3-11e8-933e-69e90b745b0a](https://user-images.githubusercontent.com/37016180/43893024-9341dc2e-9c08-11e8-9080-514dc88a03ba.png)

率直にこのまますることもあるが可能ならば完璧な形にしたい。アイコンは毎日見るのだ。 もっと完璧にしたい。

**Comment by bellflower2015** [comment]
Windows10用にrebuildしたのでscreenshot貼っておきます。

![screen shot 2018-08-09 at 20 26 11](https://user-images.githubusercontent.com/12813420/43896277-3efd080e-9c13-11e8-9dde-7ee8a4fb22d2.png)
![screen shot 2018-08-09 at 20 26 27](https://user-images.githubusercontent.com/12813420/43896284-42ec33e0-9c13-11e8-9e8f-bad25f1925a2.png)
![screen shot 2018-08-09 at 20 26 37](https://user-images.githubusercontent.com/12813420/43896288-45bc5afa-9c13-11e8-87f0-10b595a2cb4d.png)
![screen shot 2018-08-09 at 20 26 49](https://user-images.githubusercontent.com/12813420/43896290-483be6a6-9c13-11e8-994c-fe3f005a4bb2.png)
![screen shot 2018-08-09 at 20 31 05](https://user-images.githubusercontent.com/12813420/43896295-4b97b00a-9c13-11e8-822f-34cc3db304fa.png)

**Comment by bellflower2015** [comment]
Windowsのアイコンが変わらないとき：

1. アイコンキャッシュを削除してPCを再起動する
2. ショートカットを作成して、ショートカットから起動する

で直りました。

**Comment by yenxrutile** [comment]
![1](https://user-images.githubusercontent.com/36980340/43937101-ae54e6d0-9c96-11e8-9416-902e0b45d6d8.png)
![2](https://user-images.githubusercontent.com/36980340/43937102-b016b0b6-9c96-11e8-9c90-921ee48937b7.png)
オリジナルのグラデを維持しなくて良いのなら、ベース暗めで、左上にハイライト入れてぐるっと周囲光入れるとダーク、ライト両方に対応出来る可能性があるかなーと思いました。
既に検証済みでしたら、すみません。

**Comment by qi777xj** [comment]
Hello, I'm using i3wm + polybar as my GUI environment. And my OS is Funtoo Linux.
I've built and installed BitZenyPlus in feature/symbol branch.
When I first ran it, the background of applet was black and the BitZeny icon was white with some gradation (I have no screenshot about this. I'm sorry). Then, I restarted the polybar, and the applet's shape became its original shape like below.
![2018-08-10-124316_99x26_scrot](https://user-images.githubusercontent.com/12796327/43937834-0e6832ee-9c9b-11e8-9877-793f7d0a85c6.png)

**Comment by cryptozeny** [comment]
@qi777xj thanks for reporting
