### ISSUE TITLE
SplashWindowのコピーライトと、ロゴがかぶっている

### ISSUE THREAD

**Issue by zinntikumugai** [bitzenyPlus/BitZenyPlus#24]
![bzp](https://i.gyazo.com/c635441b656ad075c381cf50b8b1be04.png)
![btc](https://cdn.discordapp.com/attachments/474283531112284160/476025947167129600/Screen_Shot_2018-08-06_at_22.56.40.png)
コピーライトとロゴがかぶり、見づらくなっています
BTCのSplashWindowではアイコンが明るい関係で見えますが多少の修正を入れたほうがいいかと思います

**Comment by cryptozeny** [comment]
do you mean ` (C) ` ??

**Comment by zinntikumugai** [comment]
@cryptozeny 
Yes
`©`

**Comment by cryptozeny** [comment]
![screenshot from 2018-08-07 03-06-42](https://user-images.githubusercontent.com/37016180/43733241-f4b45c3c-99ee-11e8-8a60-543449fccea0.png)

**Comment by cryptozeny** [comment]
![bitcoin core testnet _120](https://user-images.githubusercontent.com/37016180/43782865-45e10054-9a9b-11e8-9075-7551c197226f.png)
![bitcoin core _121](https://user-images.githubusercontent.com/37016180/43782942-70a7dc5e-9a9b-11e8-8179-7a4b44740246.png)

no problem `bitcoin 0.16.2` on ubuntu 16.04

**Comment by bellflower2015** [comment]
現状、元素材は
「直径910px + 上下左右margin各57px」です。

直径を2〜4px小さくして再度確認してみようと思います。

**Comment by bellflower2015** [comment]
ところで
Ubuntuならかぶってないみたいなんですよね。
https://twitter.com/9werty60y/status/1026436814972760064
bitcoin側の基準がそういう事なんだろうと思います。
（修正はしようと思う）

**Comment by bellflower2015** [comment]
#22 にてぐれん氏に提案いただいたロゴと同じマージン比率にしてみました。
![bitzenyplus_splash](https://user-images.githubusercontent.com/12813420/43896793-fada4b4e-9c14-11e8-9e4d-854a041ee4bf.png)
