### ISSUE TITLE
"BitZeny Core" という表記について

### ISSUE THREAD

**Issue by bellflower2015** [bitzenyPlus/BitZenyPlus#27]
`BitZeny` という表記は `BitZenyPlus` に置換すべきなのは明白だが、
`BitZeny Core` という表記は `BitZenyPlus Core` にするのか？

**Comment by onokatio** [comment]
たぶんそれが一番いいんじゃないですか

**Comment by hitobb** [comment]
coind + qt = Coreという意味で使うのであれば、
```BitZenyPlus Core```でお願いします。

開発チームという意味であれば、
```The BitZeny Core developers```を
```The BitZenyPlus developers```
に、変更したいです。

**Comment by bellflower2015** [comment]
質問の意図は前者です。了解です。
