### ISSUE TITLE
dependsのQtのダウンロードURLが404 Not Found

### ISSUE THREAD

**Issue by sesameoil** [bitzenyPlus/BitZenyPlus#28]
[/depends/packages/qt.mk 3行目](https://github.com/bitzenyPlus/BitZenyPlus/blob/v3.0-dev/depends/packages/qt.mk#3)の
`$(package)_download_path=http://download.qt.io/official_releases/qt/5.7/$($(package)_version)/submodules`
のURLは404 Not Foundであるため、修正する必要がある。

Fallbackして[https://bitcoincore.org/depends-sources](https://bitcoincore.org/depends-sources)から必要ファイルをダウンロードすることも可能ではあるが、非常にダウンロードが低速であり、かつファイルが破損しやすい（ハッシュ値が合わないときがあった）。
そもそも、Fallbackは常用するものではない。

アーカイブの[https://download.qt.io/archive/qt/5.7/5.7.1/submodules/](https://download.qt.io/archive/qt/5.7/5.7.1/submodules/)から必要ファイルを取得することが妥当だと考えられる。
（このアーカイブは、BTCv0.16.2rc1から[BTCのqt.mk](https://github.com/bitcoin/bitcoin/blob/v0.16.2rc1/depends/packages/qt.mk#3)で使用されている。）

**Comment by kazu0617** [comment]
（対象の問題に関して修正されたものがマージされたため、Closeしました。）
