### ISSUE TITLE
【アンケート】アンチGPUの為のYesPower 1.0採用（HF)について

### ISSUE THREAD

**Issue by hitobb** [bitzenyPlus/BitZenyPlus#34]
# 趣旨

BitZenyの
「CPUコインとしての特長を進化させるために、
　YesPowerをデプロイしてHFしてGPUを排除する」
必要があるかどうかのアンケートとなります

# 前提

本議題に対する方針の再確認です。

https://github.com/BitzenyCoreDevelopers/others/issues/24

2018年5月の議論「アンケート1」の結果では、
「準備不足なので宣言なし、継続協議」という結論になったかと思います。
（「アンケート2」の別名採用は実施済みです）

３ヶ月たちましたので、議論を再開したいと思います。

# 確定事項

ターゲットアルゴリズム：
YesPower 1.0 　(※Argon2d案、Lyla2zoin案は廃案)

もしYesPower 1.0が採用された場合は、ハードフォークになります。
しかしながら同時にすべての取引所に対して、yescrypt 0.5採用coindの廃止を依頼しますので、
「HFによりコインが２倍になり、売買利益が出る」と、
お考えの方がいらっしゃいましたら「そのような事実は絶対に起こりえません」と明言しておきます。
お手持ちのコインは自動的にYesPower 1.0採用版に移行します。
また「全ユーザ/全プールのwallet入れ替え」が必要になります。

もしYesPower 1.0が採用されなかった場合は、現状維持になります。
すなわち、
 - BitZeny(yescrypt 0.5)
 - BitZenyPlus(YesPower 0.5 : yescrypt 0.5完全互換)

にて、動作いたします。
「全ユーザ/全プールのwallet入れ替え」の必要はございません。

# アンケート内容

YesPower 1.0の採用に

（１）賛成
（２）反対

9月15日正午までとします。
皆様、よろしくお願いいたします。

**Comment by hitujinvng** [comment]
YesPower 1.0の採用に賛成です！

**Comment by Lesmiscore** [comment]
やって良いと思いますよ
賛成で

**Comment by bellflower2015** [comment]
現状では反対。
ひとまずYesPoWer 0.5版リリースを成功させましょう、話はそこからだ。

「そのような事実は絶対に起こりえません」については
全然関係無い人が突然、2.xのソース引き継いで「BitZeny Classic」とか名乗って上場させたら絶対ではなくなるね。

**Comment by yossi1114net** [comment]
賛成です。

**Comment by onokatio** [comment]
次のリリースまで保留で

**Comment by iwa-kasoutuuuuuka** [comment]
現時点では保留。

一定期間ごとにアンケートを取ること自体は次々世代の開発をアピールにもつながるので反対はしません。(むしろイイことです)
しかし現時点では直近のPlusの開発やリリース後の運用、広報に注力した方がいいと思うため
議論だけ先走る必要性が感じられない。

またYesPoWer 1.0の採用に関して、メリットとデメリットがあまり見えないのが残念。
メリットはGPUマイニング排除だけでしょう？

**Comment by nonashi01** [comment]
1ホルダーとしてはマイニングプールや上場している取引所にちゃんと対応して頂けるかの根拠がいまいち見えてこなくて不安なので、自分も現状では「反対」で
一先ず互換性のあるYesPoWer 0.5版出してから必要性を探った方がいいと思います
マイニングプールも取引所もHFに即対応して頂ける有力な裏付けがあるなら、判断は他の方に任せたいと思います

**Comment by hitobb** [comment]
皆さんの意見がある程度、出揃ってきたので、
ワタクシの個人意見を。

『明確に反対』です。

BitZenyは「yescrypt 0.5」と共に育って来ています。
互換性があり、同期高速化＆メンテナンス性向上のメリットがある
「YesPoWer 0.5」までは許容できます。
しかし、GPUとCPUの性能差が10倍未満のこの時点で、
アルゴリズムの変更まで着手する必要性は、感じていません。

その他、BitZenyの取り得た「IF」の選択をした、
他のコインが現れて来ている事も、理由の1つに上げさせていただきます。

---

- BitZeny 1.xのチェーンを、ゼロリセットしたらどうなるか？
　  →yenten

- CPU Miningコインに暗号化機能を付けたらどうなるか？
　  →KOTO

- BitZeny 2.xのチェーンを、ゼロリセットしたらどうなるか？
　  →JagariCoinR（消えたけど、、、）

- BitZeny 2.xチェーンを、YesPoWerにして、
  かつ、チェーンをゼロリセットしたらどうなるか？
　  →いくつかのプロジェクトが動いています。

---

新しい技術に触れたい方、古参の在庫問題を回避したい方々には、
BitZenyではない「新しい選択肢」が与えられています。
この現状で、BitZenyが新コインと同じコンセプトを、
「過去のブロックチェーンを引き継いだまま」
実施するメリットが感じられません。
正直、負けると思います。


BitZenyには、今まで通り、日本語情報の豊富な入門者
（プログラマーさんののみではなく、デザイナーさんも含みます）
の受け皿としての道を歩ませてあげられないでしょうか？

以上、乱文、失礼いたしました。

※今まで通り、旗振り役としての仕事は継続しますが、
　ワタクシ個人としての意見は、こちらに示した通りになります。
　よって、YesPoWer 1.0 HFにおいて、ワタクシは開発メンバーには加わりません。

**Comment by sesameoil** [comment]
現状では反対
* 未だにz1.1.0を使用するユーザーがいる現状ではHFは極めて困難
* 広報体制も整っていない  

この二点が主な理由

**Comment by cryptoeth101** [comment]
賛成です。

**Comment by bitzeny-yay** [comment]
賛成です  
・BitZenyからBitZenyPlusに名前が変わるのに中身が変わらないとなれば初代開発者と決別した意味がない  
・z1.1.0ユーザーには現在進行形で十ニ分に広報を行っているにも関わらず、更新しないのであれば切り捨てるべき  
・GPUとCPUの採掘速度云々より「リブランド」として捉えれば導入すべき

**Comment by onokatio** [comment]
ゼロからyespowerを使ったCPU耐性のある新しいコインを作成、現bitzenyと新コインを100:1の比率で1 way peg(burn)して換金できるようにする、最後に現bitzenyチェーンは破棄という案。妄想だけど。

**Comment by onokatio** [comment]
ここで話すことじゃないですね、すみません

**Comment by hitobb** [comment]
@onokatio 

その案も考えたんですけど、ゼロから再スタートした時点でそれはBitZenyではないナニカだし、スワップする必要なくない？に行き着いた。

スワップしないとした場合、後発のYesPoWer採用コイン勢の伸び代潰すだけの老害になるにゃ～

かくて、妄想で終わってしまったwww

**Comment by ccmikami** [comment]
ただの１ホルダーですが意見させていただきます。
私は現状の案なら反対です。
YESPower0.5と1.0の明確な違いも調べてませんが、HFして事実上起こることって
１．Znyが消えてZnyPlusになること
２．いわゆるHF（BTCから分岐してBCHが生まれるみたいな）ではなく事実上のリブランドに見えること
３．アルゴリズムが変更されるためにウォレットや取引所がなんらかの対応を迫られること
だと理解しています。（そもそもずれてたらごめんなさい）

１と２はほぼ同じことかもしれませんが、hitobbさんのように開発者さん側で意見が割れているのなら「ZNYを消す」必要性が全く感じられません。それならチェーンの分岐のようにすればいいだけではないでしょうか（ZNYがそもそもそういう仕組みじゃなかったらごめんなさい）

２に焦点を当てると、現状の知名度や時価総額などを考えたら、皆さんの興味がどこまでついてくるかも疑問です。すでに上場しているCoinExchangeなどはすぐに対応するかもしれませんが、もにゃなど個人開発のウォレットは中々対応できないかもしれません。
「ホルダーに何かをお知らせする機能」は通貨にはないので、ここを見ていないホルダーはそれだけで混乱すると思うのです。
（文章の流れで思いつきを書きましたが「お知らせ機能」実装できたら便利・・・）

３のアルゴリズム変更についてはもうプログラマーから転職して何年も経っていて、知識がついていけてませんのでコメントは避けたいと思います。

最後に雑感？ですが、私にとってはMONAに続く国産通貨として20円くらいで買った超含み損通貨ですが、手放さずにこの1年近くなんとなく見守ってきた通貨です。
hitobbさんのように、この案が開発者さんが抜けていく案なのかという点も悲しいですし、価格は下げていてもオダイロイドやtipbotなどで少しずつ知名度が上がってきていると感じていた矢先に事実上のリブランドは「迷走」しているようにしか思われないと考えます。

よって今はまだその時じゃないのでこの案には反対です。
↑で書いたような分岐のHFでZNYとZNYplus共存の道を各々の開発者さんがたどれるなら、それは賛成です。

長文・乱文で恐縮ですが、１つの意見として読んでもらえれば幸いです。

**Comment by Tanisun** [comment]
ホルダーとしては

「反対」

なのですが、個人的な想いとしては、私の全く想像すら追いつかない世界の技術追及の話となれば、新しい取り組み、新しい道を選んでいく事にワクワクテカテカして油取り紙が無くなってしまいそうなくらいのものだろうなぁという想いもあります。

反対理由は、やはり市場の混乱が想定される事ですかね。でも、冷え切っている仮想通貨界隈にぶっこみを掛けるには良い素材にもなりそうな気がしないでもないと葛藤している部分もあります。

余計な事書いているかもしれません、ごめんなさいｗ

**Comment by zenywallet** [comment]
CPUでマイニングしようとする人のモチベーションがどれだけ損なわれているかということを考えてみると、猫も杓子もBitZenyをCPUマイニングしている状況のようなのでそれほど影響が出ていない気がします。
GPUで攻略しようという人のモチベーションも技術の発展には重要なので、早急の対策は望ましくなく緩やかな対応が良いと思います。
BitZenyをもっとマイニングしようとGPUを手にしてしまった人は、GPUでマイニングできるたくさんの仮想通貨がある大海原に旅立つことになり、BitZenyはその橋渡し役になれますし。


ハードフォーク周りのストーリーとしては、

(1) ハードフォークしない。
(2) 2つの通貨に分岐せずにハードフォークする。(みんなで新バージョンへソフトウェアアップデートする)
(3) 2つの通貨に分岐してハードフォークする。(Bitcoin、Bitcoin Cashのような感じ)

(2)を実現するには、BitcoinのSegWit投票のようにマイナーやノードによるシグナリングによってアクティベートする仕掛けにしておけばよいと思います。
ただ分岐を阻止するには高い閾値が必要になると思います。創始者がハードフォークをするという意思を示せば容易に成功する可能性があると思いますが、そうでなければ分岐してしまうかもしれません。
様々な活動によっていろいろカルマも溜まっているようなので(2)の実現が難しくなっていると思います。BitZeny神社もできることですし、訪れてみるとよいでしょう。

現在BitZenyはソフトフォークしかアクティベートされていませんので、これまでの全てのBitZenyソフトウェアと後方互換性があります。
大多数のBitZenyユーザーはアップグレードする必要がなく、現段階でz1.xから移行していないユーザーがいることを気にする必要はないと思います。
それにもかかわらず、まるでBitZeny 2.xが既存のソフトウェアに必要なアップデートであるかのように誤解させる事態になっていることの方が問題だと思います。
そういったことの小さな積み重ねが(2)の実現を困難にしていると考えています。

(3)に関して、付加価値を付ける方法はいろいろあると思いますので、ハードフォークの新通貨が必ずしもオリジナルを超えられないということはないと思います。
通貨が分岐すると理論上価値が下がると言われているようですが、実際のところどうなのかというところです。アイディア次第だと思います。


yescryptがGPU攻略されることがあったらyescryptを改造するくらいしか道がないと考えていたので、solardiz氏がPoW用途の利用に興味を持ってくれないかなと思っていましたが、現状のsolardiz氏の想像以上の対応に驚いています。
yespowerのテストプログラムには、yescryptファミリーのすべての仮想通貨のパラメータを用意している程の丁寧っぷりです。BitZenyのgithubにも遊びに来てくれました。とても紳士的な方のようです。
BitZenyは、yespowerコンソーシアムに参加し、将来的な問題の解決に協業していくべきだと思います。
yespowerはIntelのCPU機能を最大限に引き出すことによって実現しているので、そのうちIntelが興味を持つのではないかと思います。


(2)のストーリーを目指す場合、今すぐにハードフォークしてまで必要だとは思わないので採用に反対ですが、継続的に採用を検討すべきだと思います。
(3)のストーリーを目指すなら採用に賛成。

**Comment by GitHubCoinSap** [comment]
反対
GPUで掘れなければ相手にしない通貨。
それに現ホルダーが少ないのに、全員に今までの物が使えないとなって良い効果があるとは思えない。
HFは０からのスタートになるだけでは？この時期に０からのスタートでは相手にされないと思う。

**Comment by surezu** [comment]
神社の中の人として意見させて頂きます。
「反対です」
今やるべきでは無いと思っております。
それなりにわかっている人ならいいのですが、
BitZeny神社プロジェクトチーム及び関わっている方、市役所、議員、一般市民、森林組合、
ほとんどがBitZenyが初めての仮想通貨であり、なんとなくわかっている人にHFだのこうだのを説明し、
支持お願いします。
という事をするとかなりの混乱が予想されます。
混乱により、支持されない可能性も十分にあります。
HFせずに現状維持で知名度を上げ、より沢山の方に参加してもらい、盛り上げる方が先ではないかと
思っております。

今後のBitZeny神社としての活動に大きく影響しそうでしたので意見させて頂きました。

**Comment by kaminuma** [comment]
反対です。

もらもろの反対理由は、反対派の人と同じですが、現状はホルダーの基礎的な知識面での定着活動を継続し(全然してなくてすいません)、GPUによる驚異が許容をオーバーしたタイミングで移行に踏み切るくらいで良いのかと思っています。

早い流れにファンやホルダーが置いてきぼりになってしまっては、本末転倒であるかなと。

すべてのコインでそうですが、開発者、投資者、ファン、それぞれが完全に足並みをそろえることはできなくとも、うまく歩みよりしながらやれたらいいね☆

て、ことで反対票。

**Comment by kazu0617** [comment]
長期的には賛成です。

現実問題BitZenyDevelopers段階において行っていた、[0Feeの排除]に関しても、ソフトフォークとは公には言っていましたが、アレに関しても本来であればHFする危険性を孕んでいました。しかし、知られているように今は2.x世代がデファクトスタンダードとなっており、0Feeに関しては少なくともDiscordには問い合わせされることがなくなりました。
知識面の問題であれば「ウォレットがアップデートされるからいついつぐらいまでには更新してねー」といったPOPで十分なところもあり、0Feeのタイミングと特段状況は変わりません。

また、ここでBitZenyの歩みを止めるべきなのか、と言ったことを考えるとどこかの方向には進み続けなければ行けないと（少なくとも自分自身は）思います。が、yescryptの開発は既に止まってしまっている上、現状ではCPU<GPUになってしまっており、またこれが逆転する未来が少なくともyescryptではありえません。そういった現状を鑑みると、YesPowerに移行して、少なくともBitZenyの最初に立ててあった柱である[GPU<CPU]を守り続けるために歩むべきなのではないか…
と思います。

最も、0Feeのタイミングと同様、十分な周知なしでは本当にチェーン分岐擦るのでそこは周知して進めつつといった感じで十分なスパンを持ってすすめることが前提にはなりますが。

と言った感じの気持ちなので、長期的賛成といった感じです・ω・)

**Comment by zinntikumugai** [comment]
賛成だが採用は __長期的に行う必要がある__

賛成としては
- BitZenyの`CPUでも掘れる`が現状は成り立っているが比較的難しいになっている
- いくつかYesPowerを採用した通貨及びPoolが出ているため時間をかければなんとかなる

反対意見を上げるとしたら
- すべて入れ替えのコストが大きい
   - Pool
   - 取引所
   - 外部サービス ..etc

- 新たな管理体制を取り、運営していかなければならない
    - (現在のままではやる人がいなければ終わり状態)

どちらに転んでも
- 価値がどうなるかは分からない

---

## ホルダーとして
Walletの入れ替えは正直めんどいです(サービス提供用VPSいっぱいあるので)
ただ、いつまでも同じ物を使い続けるのは違うかな、定期的にリリースがあってほしいとも思える(あくまでもリリース周期の話)ので、いい機会かなと

## Minerとして
大歓迎
採掘できる系GPUを保有しない私としては迷惑だったので
他の通貨が掘れないんでBitZenyに来ました的な人は悪いですが他にも通貨がありますし、
`GPUで掘れなければ価値がない`という意見も`GPUで掘れる`だけで決めつけないでもらいたい(そもそもBitZenyの方針としては誤り)

## Discordの管理者として
できれば近場の修正(主にロゴ)を先にリリースしてほしい(Walletをベースとしてるので)
最近はチャットが完全凍結状態なので話すネタが欲しいとも言えますが
(まぁ私の管理不足とも取れますが)

## Pool運営者として
Wallet等の入れ替え等の作業がありますがYesPowerを採用した通貨のPoolの誕生や情報共有もあり比較的対処は出来ると思います(強いて言えばMOPSかな)
`NOMP`は`zny-nomp`,`yiimp`も他通過のコードを参照すれば修正できないことでは無いと思います
ハッシュレートの低下はどちらにしろなんとも言えません。
Poolを提供していますが掘ってもらっているわけで、掘っている人を制御しているわけじゃないので

### BitZenyは消えません
他の方が`BitZenyは消えてしまう`等の意見がありましたが、Miningをする人、Walletの同期をする人がいればチェーンが続きます
人のプールとしては両方とも採用するのもありかなと(継続してBitZenyを残したいという方向けに)考えています(取引所の方は難しいですが)
最終的に採用されるかは状況次第ですがBitZeny、BitZenyPlus両方を支持するつもりです

---
あくまでも長期的に見たらの話、今すぐやりますと言うなら反対(というより持ち越し)です

**Comment by GitHubCoinSap** [comment]
BitZenyの価値はどうでも良いのよ。
俺には価値がないだけで、「頑張ってね、さようなら」というだけで。

**Comment by GitHubCoinSap** [comment]
何となく大きな勘違いがありそうなので。
他が掘れないからBitZenyに来ることはまずないと思う。
今日時点でも、掘って売るということの利益考えたらMONAの方が上。NiceHashのような所もあるわけで。
BitZenyを掘りたいから掘っている。CPUではかなり前から掘っているしね。

**Comment by bitzenywork** [comment]
私はホルダーの立場として、反対です

**Comment by MTR1659** [comment]
現時点では「反対」です。
GPUで掘れるとは言っても、圧倒的な差があるわけではないかなと思うので。たぶんGPUだったら他の通貨を掘ったほうが効率もいいでしょうし。
まずはyespower0.5にして様子を見るのがいいかと。
ただ、yescryptの考案者が協力的で、今後yespower1.0をアップデートしていくとのことであれば、そのアップデート内容によっては今後1.0系を採用することも考慮していくのはありだと思っています。

**Comment by balloonfc-hub-git** [comment]
こんにちわー。
私は「反対」です。

CPUで掘る意味がない位GPU有利になれば必要かもしれませんが、今はそこまで気にする必要はないと思います。

SFでできるなら良いかもしれませんが、HFして取引所やユーザーに負担をかけてまですることではないと思います。

Bitzenyにかんぱーい🍺

**Comment by nagasench** [comment]
「反対」

**Comment by tsukky1337** [comment]
賛成です。
BitzenyはCPUでしか掘れない事に意味があると思っています。

一般的に広く使われるパソコンやスマホで掘れる事で一般人に広く普及し、対等な分散管理に貢献している事を実感出来ると思うからです。

明らかにパワー差を感じてしまうと、特別なマシンを持っていない側からすればネットワーク維持に貢献している実感もなく、ただコインのおこぼれをもらっているだけでマイニングの必要性を感じられないです。

**Comment by hitobb** [comment]
アンケート期間の期限が来ました。
皆様、ご協力、ありがとうございました！

投票結果を鑑みると、賛成反対が半々。
また、現在は反対だが継続して検討は必要との意見が複数ありました。

したがって、今回の結論は「現状維持、及び、継続審議」です。

3カ月後、12月頃に再アンケートいたします。
引き続き、よろしくお願いします！

**Comment by iotkaden20230322** [comment]
zPoolでの取り扱い終了してしまいましたね
