### ISSUE TITLE
【アンケート】[2018/12]アンチGPUの為のYesPower 1.0採用（HF)について

### ISSUE THREAD

**Issue by hitobb** [bitzenyPlus/BitZenyPlus#44]
# 趣旨

BitZenyの
「CPUコインとしての特長を進化させるために、
　YesPower 1.0 をデプロイしてHFしてGPUを排除する」
必要があるかどうかのアンケートとなります

# 前提

本議題に対する方針の再確認です。

https://github.com/bitzenyPlus/BitZenyPlus/issues/34

2018年9月の結果では「継続協議」という結論になったかと思います。

3ヶ月たちましたので、議論を再開したいと思います。

# 確定事項（アップデートあり）

・YesPowerの採用（BitZenyPlusのみ）

・yescrypt0.5の継続（BitZeny 2.x のみ）

・新機能実装はBitZenyPlusのみ

・BitZeny 2.x のメンテナンスは継続

・取引所やPoolへのアナウンスは、BitZenyPlusがHFすると確定した時点で検討

# 議論部分：

以下、どちらの方式にするか。

・YesPower 1.0

・YesPower 0.5

もしYesPower 1.0が採用された場合は、ハードフォークになります。
しかしながら同時にすべての取引所に対して、yescrypt 0.5採用coindの廃止を依頼しますので、
「HFによりコインが２倍になり、売買利益が出る」と、
お考えの方がいらっしゃいましたら「その可能性は極めて低いです」と明言しておきます。
（件のBitCoinCASH分裂のような事態が起きる可能性もあるので、ゼロではありません）
お手持ちのコインは自動的にYesPower 1.0採用版に移行します。
また「全ユーザ/全プールのwallet入れ替え」が必要になります。
YesPower 1.0を採用すると、GPU耐性は付きます。
3か月前と異なる点として、マルチプールが現れました。

もしYesPower 0.5が採用された場合は、ハードフォークは発生いたしません。
下位互換性が保たれるため、BitZeny 1.xを含むすべてのバージョンとの互換性が保てます。
「全ユーザ/全プールのwallet入れ替え」は必要ありません。
yescrypt 0.5をあえてYesPower 0.5に書き換える理由は、
起動速度の改善、セキュリティ性の向上です。
デメリットとして、YesPower 2.0以降では、
0.5に関する互換性が排除される可能性があります。

# アンケート内容

以下のいづれかをご回答願いたいです。

（１）BitZenyPlusは、YesPower 1.0採用

（２）BitZenyPlusは、YesPower 0.5採用

（３）今はまだその時期ではない、3か月後に継続審議

（４）その他

12月30日正午までとします。
大晦日に、こたつでぬくぬくしつつ、結果発表しましょう。

皆様、よろしくお願いいたします。

**Comment by asidlover** [comment]
（１）
広く多くの人にマイニング参加してもらう他コインとの差別化の為にも

**Comment by qi777xj** [comment]
( 1 )
I think it will be great.

**Comment by cryptozeny** [comment]
(2)

2度。私は今yesPower1.0検証中です。 HFは演技するのがいい。 yesPower0.5作業の安定性を確認し、その後にまた議論しましょう。

参考にyesPower0.5はBitZenyPlus v3.0で開発が終わった。 テストをして配布すればいいです。

先に何のリスクなしにyesPower0.5を配布して3ヵ月後に問題が発生しなければ、その時1.0 HF提案投票をまたすれば良いだろう。

**Comment by cryptozeny** [comment]
巡る議論とは別に、yesPower1.0を採用したコインはcryplyやbellcoinそして私が開発中のコイン(名前は未定)がある。 これらを比較して導入を考慮しても遅くありません。

**Comment by akashiap** [comment]
(2)を支持します。

以前は公平なマイニング機会のために
アンチASIC,GPUを強く支持していましたが、
現在の価格の状況ではマイニングよりも買った方が遥かに安く
CPUでもGPUでも参加者自体が歓迎される状況かと思います。

将来の可能性として
価格が向上しCPUよりも圧倒的にGPUやASICマイナーが
攻撃や利益を独占するような状況に対して
準備できている状態で十分だと思います。

後は現在の状況では得られる対価に対して、
ハードフォークは痛みが大きすぎるようにも思えます。

また4年以上続くPOW式の価値通貨ですので
ユーティリティトークンのように
焦って新しいものを導入する必要もないのかなと思います。
多少、状況を見極めつつ、世の中で使われて多少枯れてから導入していく安全策を取る方が
価値の棄損がないのかなとも思うようになりました。
（典型的な老害的意見でしょうか...）

後は私のようにすぐに手放せる単なるホルダーよりも
継続的な発展のためにはコア開発者やサービス開発者や
広報の方の意見を重視した方が良いと思います。

**Comment by MTR1659** [comment]
(2)派
現状GPUを過度に排除する必要はないかなと思います。
CPUでも全くほれないことも無いですし。
ハッシュレートが高くなることは悪いことでもないので。
1.0については今後も継続して検討対象にしておけばいいかなと思います。

**Comment by myaruruethanol** [comment]
(2)を支持
 あまり技術的なことはわかりませんが、仮想通貨全盛期ならともかく今GPUで掘ってもあまりメリットはありませんし、現状GPUで掘れていますがCPUで全く掘れなくなったということは無かったので。
 あと、ZNYを保持しているけどネットから阻害されている人や保有しているがZNYの状況を直ぐに把握することが難しい方もいますし、実際全ての保有者がWalletを入れ替えることは不可能かと思われます。
上記の理由で2を支持します。
言ってることがめちゃくちゃなようであればスルーしてください()

**Comment by Aeinsk** [comment]
(2)支持です。

「CPUで掘れる」が無理な程にGPU、ASICが台頭してきた場合は1.0もありかなとは思いますが現時点では1.0の利点をあまり感じません。0.5でリリースして幅広い広報を実施しある程度、一般利用者に周知、利用者新規開拓が済んだところで次期Ver.の策定としてロゴコンテストで使用した投票システムを利用して投票を行ってはどうでしょうか。
それかWin7とWin10のシェア率の差が10％超えてきたら検討を初めてもいいかもしれません。

**Comment by macyan2000** [comment]
（１）BitZenyPlusは、YesPower 1.0採用
新しいもの好きなので。
取り残されるのも嫌だし、固執するということは進化を止めるのと同義ではないかと。
個人的にはYesPowerにすらこだわる必要はなく、別のアルゴでも良いと思っています。
尚、GPUを排除するという目的だけであるのなら何もしなくていいと思います。
私はASICもクラウドも支持派なので。

**Comment by Marimox** [comment]
2. Yespower 0.5採用を支持します。

GPUマイニング可能であっても、よほどの収益性が無い限りは、CPUマイニング不可能なレベルまでハッシュレートが上がらないように感じます。BitZenyの特徴であるマイニングへの敷居の低さは維持されるのではないかという考えです(現にそうですが)。

また、先日のハッシュウォーで改めて認識できましたが、全ユーザ、サービスのウォレット更新はなかなか骨の折れることで、差し迫ってHFする必然性が無いのであれば避けた方が良いとも感じました。

将来的なYespower 1.0への更新は頭に入れておくべきと思いますが、今はその時ではないと思います。

**Comment by angel646** [comment]
（２）を支持します
テストもなしにHFして脆弱性が見つかると取り返しが付きません
一度0.5で安定性を見てからでも遅くはないと思います

**Comment by surezu** [comment]
（２）を支持します。

以前も書きましたがHFせずに現状維持で知名度を上げ、より沢山の方に参加してもらい、盛り上げる方が先ではないかと思っております。

**Comment by BitzenyDevTeam** [comment]
（２）支持

Discoでの話を含めて総合判断として。

**Comment by onokatio** [comment]
今は（2）を採用して、その後（1）案について改めて考えるのに一票。

**Comment by yossi1114net** [comment]
( 1 ) に賛成します。

**Comment by balloonfc-hub-git** [comment]
（３）です。
現状（１）を行うのは現実的ではないと思います。
とはいえ、（２）のメリットが強いかというと微妙なので継続審議で。

**Comment by iwa-kasoutuuuuuka** [comment]
（２）BitZenyPlusは、YesPower 0.5採用！

将来的にはGPU耐性をつけるべきだと思いますが、現時点ではハードフォークによる混乱は避けるべきだと思います。取引所やプールの対応もあるので。

**Comment by hitobb** [comment]
個人としての意見を。

（２）BitZenyPlusは、YesPower 0.5採用

ですね。
皆さんとの合意が大前提ですが、まずは一つ、リリースしてしまいたい。

**Comment by nagasench** [comment]
（２）支持です。
YesPower 1.0のほうは様子をみた方が良いと思います。

**Comment by kurokuku** [comment]
（2）ハードフォークが…

**Comment by kojisarukawa** [comment]
（２）を支持します。

**Comment by hitobb** [comment]
みなさま、様々なご意見、ありがとうございました！
アンケート、締め切ります！

**Comment by zinntikumugai** [comment]
大遅刻()

> (2) YesPower 0.5 の採用

最終的にはHFする方向なのでまずは足並みをそろえてから行う感じに

**Comment by hitobb** [comment]
アンケートご協力、ありがとうございました!

今回の結論は「（２）BitZenyPlusは、YesPower 0.5採用」です。
ただし、将来的にYesPower 1.0継続の意見もありましたので。3月くらいに別テーマとしてアンケートします。
みなさまの合意あってのBitZenyです。

2019年はBitZenyPlus開発開始の年です。
みなさま、よろしくお願いいたします。
良いお年を！
