### ISSUE TITLE
BitZeny segwitアドレスの頭文字について(BIP173,Bech32 human-readable part)

### ISSUE THREAD

**Issue by hitobb** [bitzenyPlus/BitZenyPlus#49]
# 趣旨

BitZenyのベースソースを、bitcoincore 0.16以上に更新する際、BIP173 Bech32 Human-readable partの定義を行う必要があります。

https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki

本議題は、BIP173 Bech32 Human-readable partの選定に関するissueです。

# 確定事項

過去にbitcoin core 0.16以上をベースとして開発されたBitZeny coreは、少なくとも2つ存在しています。それぞれ、以下の組み合わせでソースが記載されています。

Case 1.
  「sz」「tz」「rz」

Case 2.
 「bz」「tbz」「rbz」

また、satoshilabs/slipsでは、以下のPRにより、下記のように登録されています。
 「zeny」「tzeny」「rzeny」

https://github.com/satoshilabs/slips/pull/569

# やりたい事

皆様の意見を取り入れたうえで、satoshilabs/slipsの内容を修正いたします。

https://github.com/satoshilabs/slips/pull/569

# How To

2018年12月までは、GitHub issueによるアンケートを実施しましたが、過去に「敷居が高い」というご意見がありましたので、Google フォームによるアンケート形式を採用しました。

参考：
https://github.com/BitzenyCoreDevelopers/others/issues/35

アンケート結果の共有と、議論結果について、本issueにて記録を残します。

**Comment by cryptozeny** [comment]
`zeny tzeny rzeny` is good choice i think. 👍 its reasonable.

so bech32 address looks `zeny1q...`

**Comment by kazu0617** [comment]
I think so too. 
https://github.com/bitzenyPlus/BitZenyPlus/issues/49#issuecomment-477850852

**Comment by Lesmiscore** [comment]
`zeny tzeny rzeny`でいいのではないでしょうか
直観的ですし分かりやすい

**Comment by zinntikumugai** [comment]
![image](https://user-images.githubusercontent.com/16275962/55372263-129a1f80-553c-11e9-949f-eb8e654fb18d.png)
アンケートはこちらの通り

**Comment by zinntikumugai** [comment]
![image](https://user-images.githubusercontent.com/16275962/55372721-acae9780-553d-11e9-95f4-8c838bc1c729.png)
bz/szのアンケート

**Comment by zinntikumugai** [comment]
私からとしては
https://github.com/satoshilabs/slips/pull/569
こちらの内容は
- 非公式のものであり、十分な協議が行われていない
- また、一部マイニングプールではアドレスチェックの項目で修正が必要になる場合が多いと思われる(特にNOMPから直接修正しているプールは影響が大きいと思われる)

また、BTCかLTCかになるがBitZenyはBTCフォークなのでLTCフォーク通貨に多いLTC方式は無いかと
よって、BTCフォーク方式のCase1 かなと

**Comment by zenywallet** [comment]
zenyが直感的で分かりやすいというのはもっともな意見だと思います。Monacoinはmonaですし。

ただbitcoinのポリシーを尊重するなら、短いほうがよさそうということのようです。
bitcoinのhuman-readable partがbtcでなくbcであるのは、bcの方がより短いからとあります。

開始アドレスがzだと開始Zのアドレスと紛らわしいという理由もあるようです。
だとしたらbで始まるアドレスはbitcoinと間違える可能性があり、それも問題視すべきかも。

そのほか、Zenyという文字列は、国内では商標登録出願されているので使えないという理由があるようです。
しかしながら、Zenyの商標出願は今のところ拒絶査定になっています。今後どうなるかはまだ分かりませんが、我々は昔からゼニーと呼んできたわけですし、現段階ではその行動を変えるべきではないと思います。


1年位前にプレフィックスがszと決定され、すでにそれに従ったBitZenyのウォレット等がその頃から存在しています。
また、szアドレスへ送信されたとも思われるトランザクションも実際に存在しています。
コインの送受信は、受信者側のウォレットのアドレスを送信者に教えて、送信者側のウォレットからコインを送信してもらうわけですが、受信者のウォレットと送信者のウォレットのプレフィックスが一致していないと、アドレスが違うので送信できないということになります。
異なるプレフィックスのウォレットが公開されてしまったことやzenyがslip-0173に登録されてしまったことによって、もはや複数のプレフィックスをサポートしなければいけない事態になっているかもしれないことをとても残念に思います。

**Comment by hitobb** [comment]
みなさま、ご意見ありがとうございました。

最初に実施すべき内容は「satoshilabs/slips#569」の修正と感じます。
現状、「zeny」「tzeny」「rzeny」を実装しているcoreは存在していない為、
なるべく早い段階で修正して影響範囲を小さくする必要があります。

アンケート結果を鑑みた結果、
「bz」「tz」「rz」
を提案したいのですが、いかがでしょうか？

※私個人としては、既存組み合わせである
「sz」「tz」「rz」
が理想ですが、アンケート結果は絶対だと考えています。

**Comment by zinntikumugai** [comment]
特に問題はありません

**Comment by bellflower2015** [comment]
「bz」「tz」「rz」で異議ありません 👍
