### ISSUE TITLE
z3.0.x change "User Agent" Name

### ISSUE THREAD

**Issue by cryptozeny** [bitzenyPlus/BitZenyPlus#5]
This simply changes the name displayed on the network, and it helps to check the version of client.

https://github.com/bitzenyPlus/BitZenyPlus/blob/efd7833970a55e65a3b318ab99483335332ac411/src/clientversion.cpp#L16

change `Satoshi` to `bitzenyPlus`

**Comment by cryptozeny** [comment]
applied

**Comment by hitobb** [comment]
When one user opens more than one PR, it becomes difficult to manage the source. Let's do it later.
Please list it as ToDo in the issue.

**Comment by hitobb** [comment]
I confirmed that this change has been set.

Next time,
please separate commit and give it an easy-to-understand name.

**Comment by cryptozeny** [comment]
i totally understand. you are right. i will be careful! this update should be next time.

**Comment by cryptozeny** [comment]
`bitzenyPlus` or `BitZenyPlus` or `bitzenyplus` ??

plz confirm this! @hitobb @bellflower2015

**Comment by kazu0617** [comment]
hitobb said "BitZenyPlus" is formal name. #15
(At GirHub OrgName, original BitZeny author use "bitzeny" at GitHub, so he use "bitzenyPlus" when he create GitHub Org.)

**Comment by bellflower2015** [comment]
https://github.com/bitzenyPlus/BitZenyPlus/blob/v3.0-dev/src/rpc/net.cpp#L93
https://github.com/bitzenyPlus/BitZenyPlus/blob/v3.0-dev/src/rpc/net.cpp#L423

**Comment by kazu0617** [comment]
マージされたため一まずクローズといたします。
