### ISSUE TITLE
[v3.0-dev] no peers at startup 

### ISSUE THREAD

**Issue by cryptozeny** [bitzenyPlus/BitZenyPlus#51]
i had to do addnode. we need at least DNSseeder or hardcoded peerlist

**Comment by fujiwaraizuho** [comment]
I can build DNSSeeder but I don't have a hardcoded v3.0.0 peerlist

**Comment by bellflower2015** [comment]
It seems necessary to consider which node is the official node.
So I don't think this problem can be decided now.

**Comment by cryptozeny** [comment]
v3.0 node is compatible with z2.x 

its just yespower 0.5 update

**Comment by cryptozeny** [comment]
> So I don't think this problem can be decided now.

however we should fix this issue anyhow.

> I can build DNSSeeder but I don't have a hardcoded v3.0.0 peerlist

could you build the DNSseeder? if you done, please tell us. we can hardcode your seeder. if you build DNSseeder, you do not need any peerlist. it download automatically. @fujiwaraizuho

**Comment by fujiwaraizuho** [comment]
What value should you assign here?
https://github.com/sipa/bitcoin-seeder/blob/master/main.cpp#L404-L405

**Comment by cryptozeny** [comment]
check this @fujiwaraizuho 
https://github.com/sipa/bitcoin-seeder/compare/master...sugarchain-project:master

**Comment by cryptozeny** [comment]
if you wanna host dnsseed, you have to own your vps server as nameserver.

**Comment by fujiwaraizuho** [comment]
Fork bitcoin-seeder to make it compatible with BitZeny
Setting up server
https://github.com/fujiwaraizuho/bitzeny-seeder

**Comment by cryptozeny** [comment]
good news. whats the URL?

**Comment by fujiwaraizuho** [comment]
I tried building BitZeny Seeder!
Stable operation cannot be guaranteed.

SEEDER: zny.seed.fujishan.jp

**Comment by fujiwaraizuho** [comment]
So far, this bitzeny-seeder has not separated v3.0.0 and v2.0.x nodes.
Is this a problem?

**Comment by cryptozeny** [comment]
@fujiwaraizuho awesome!
```
$ dig +short zny.seed.fujishan.jp
60.120.168.98
160.16.210.208
133.18.173.147
172.105.240.66
95.179.165.90
153.204.115.111
80.209.226.187
60.108.235.88
126.100.248.192
133.218.135.199
133.18.171.160
45.62.248.65
125.193.170.90
150.95.215.192
14.63.120.89
39.111.8.195
125.193.171.145
153.126.177.24
133.18.168.28
160.16.72.64
45.32.89.255
58.88.96.67
160.16.75.97
116.58.174.119
```

**Comment by cryptozeny** [comment]
fixed
https://github.com/bitzenyPlus/BitZenyPlus/pull/53
