### ISSUE TITLE
Add new icons 2018 version

### ISSUE THREAD

**Issue by cryptozeny** [bitzenyPlus/BitZenyPlus#8]
https://github.com/bitzenyPlus/symbol_mark

新しいアイコンがアップデートされました。 アイコンを交代するのがいいです。

テストネットアイコンも少し違うことがよさそうです。

**Comment by hitobb** [comment]
ICONを変更するときは、このコミットを参考にしてください。

https://github.com/bitzenyPlus/BitZenyPlus/commit/659981c0f2c8cb4a359b79b2f49ea5dfb206207f

コミットが作業単位で分かれているので、とても理解しやすいです。

**Comment by hitobb** [comment]
テストネットのアイコンは変更しません。
このままでお願いします。

**Comment by cryptozeny** [comment]
@hitobb テストネットのアイコンは、従来の維持(old icon)

メインネッは2018バージョン(new ver)と交代

これが合いますか?

**Comment by hitobb** [comment]
@cryptozeny 

メインネットアイコン：2018バージョン(new ver)
テストネットアイコン：2018バージョン(new ver)
メインネットアイコンと間違わないように、テストネットアイコンを変更する：No

これでお願いします。

**Comment by cryptozeny** [comment]
https://twitter.com/bellflower2015/status/1025466300900859905

@bellflower2015 このアップデートは彼の方がいいと思う。

**Comment by bellflower2015** [comment]
@hitobb 
https://github.com/bitzenyPlus/symbol_mark/blob/master/png/bitzenyplus-symbol.png
上下左右の余白が余計なので、上下左右の余白無しで 1024x1024 となるようにPNGファイルを作ってもらってください
(アイコンのビルド用。bitzenyplus-symbol.png とは別名で保存した方がよさげ)

**Comment by bellflower2015** [comment]
ついでにテストネット用アイコンも作ってもらえれば一番良いのだけど…。

**Comment by zinntikumugai** [comment]
テストネットアイコンについて、BitZenyにて議論したものがあります
https://github.com/BitzenyCoreDevelopers/others/issues/23
![1](https://user-images.githubusercontent.com/37474563/38014921-29ce4308-32a5-11e8-9c34-435ec35bd9ac.png)

**Comment by zinntikumugai** [comment]
![image](https://user-images.githubusercontent.com/16275962/43724093-28bfaaf6-99d4-11e8-84ca-7efaf3a4d264.png)
左：BitZenyTestnet、右：BitZeny
あわせて通知領域のアイコンを変更できるとわかりやすい(以前は出来てたと思いますが2.x辺りからなくなりました)

**Comment by bellflower2015** [comment]
#29 によって #22 , #24 をクローズしましたので同様にクローズします。
